#include "font.h"

#include <map>

#include "util/gfx/gfx.h"

namespace font {
using namespace color;

const auto kAlphaMap = std::map<char, Sprite>{
    {'A',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords = {{0, 1},
                               {0, 2},
                               {0, 3},
                               {0, 4},
                               {1, 0},
                               {1, 3},
                               {2, 1},
                               {2, 2},
                               {2, 3},
                               {2, 4}}}}}},
    {'B',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords = {{0, 0},
                               {0, 1},
                               {0, 2},
                               {0, 3},
                               {0, 4},
                               {1, 0},
                               {1, 2},
                               {1, 4},
                               {2, 1},
                               {2, 3}}}}}},
    {'C',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords = {{0, 1}, {0, 2}, {0, 3}, {1, 0}, {1, 4}, {2, 0}, {2, 4}}}}}},
    {'D',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 1},
                         {0, 2},
                         {0, 3},
                         {0, 4},
                         {1, 0},
                         {1, 4},
                         {2, 1},
                         {2, 2},
                         {2, 3}}}}}},
    {'E',
     {.width = 2,
      .sections = {{.color = kWhite,
                    .coords = {{0, 0}, {0, 1}, {0, 2}, {0, 3}, {0, 4}, {1, 0}, {1, 2}, {1, 4}}}}}},
    {'F',
     {.width = 2,
      .sections = {{.color = kWhite,
                    .coords = {{0, 0}, {0, 1}, {0, 2}, {0, 3}, {0, 4}, {1, 0}, {1, 2}}}}}},
    {'G',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 1},
                         {0, 2},
                         {0, 3},
                         {0, 4},
                         {1, 0},
                         {1, 4},
                         {2, 0},
                         {2, 3},
                         {2, 4}}}}}},
    {'H',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 1},
                         {0, 2},
                         {0, 3},
                         {0, 4},
                         {1, 2},
                         {2, 0},
                         {2, 1},
                         {2, 2},
                         {2, 3},
                         {2, 4}}}}}},
    {'I',
     {.width = 3,
      .sections =
          {{.color = kWhite,
            .coords = {{0, 0}, {0, 4}, {1, 0}, {1, 1}, {1, 2}, {1, 3}, {1, 4}, {2, 0}, {2, 4}}}}}},
    {'J',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 3},
                         {0, 4},
                         {1, 0},
                         {1, 4},
                         {2, 0},
                         {2, 1},
                         {2, 2},
                         {2, 3},
                         {2, 4}}}}}},
    {'K',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 1},
                         {0, 2},
                         {0, 3},
                         {0, 4},
                         {1, 2},
                         {2, 0},
                         {2, 1},
                         {2, 3},
                         {2, 4}}}}}},
    {'L',
     {.width = 2,
      .sections = {{.color = kWhite, .coords = {{0, 0}, {0, 1}, {0, 2}, {0, 3}, {0, 4}, {1, 4}}}}}},
    {'M',
     {.width = 5,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 1},
                         {0, 2},
                         {0, 3},
                         {0, 4},
                         {1, 0},
                         {2, 1},
                         {2, 2},
                         {3, 0},
                         {4, 1},
                         {4, 2},
                         {4, 3},
                         {4, 4}}}}}},
    {'N',
     {.width = 4,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 1},
                         {0, 2},
                         {0, 3},
                         {0, 4},
                         {1, 1},
                         {2, 2},
                         {3, 0},
                         {3, 1},
                         {3, 2},
                         {3, 3},
                         {3, 4}}}}}},
    {'O',
     {.width = 4,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 1},
                         {0, 2},
                         {0, 3},
                         {1, 0},
                         {1, 4},
                         {2, 0},
                         {2, 4},
                         {3, 1},
                         {3, 2},
                         {3, 3}}}}}},
    {'P',
     {.width = 4,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 1},
                         {0, 2},
                         {0, 3},
                         {0, 4},
                         {1, 0},
                         {1, 2},
                         {2, 0},
                         {2, 2},
                         {3, 1}}}}}},
    {'Q',
     {.width = 5,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 1},
                         {0, 2},
                         {0, 3},
                         {1, 0},
                         {1, 4},
                         {2, 0},
                         {2, 3},
                         {2, 4},
                         {3, 1},
                         {3, 2},
                         {3, 3},
                         {3, 4},
                         {4, 4}}}}}},
    {'R',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 1},
                         {0, 2},
                         {0, 3},
                         {0, 4},
                         {1, 0},
                         {1, 2},
                         {2, 1},
                         {2, 3},
                         {2, 4}}}}}},
    {'S',
     {.width = 4,
      .sections = {{.color = kWhite,
                    .coords = {{0, 1}, {1, 0}, {1, 2}, {1, 4}, {2, 0}, {2, 2}, {2, 4}, {3, 3}}}}}},
    {'T',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords = {{0, 0}, {1, 0}, {1, 1}, {1, 2}, {1, 3}, {1, 4}, {2, 0}}}}}},
    {'U',
     {.width = 4,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 1},
                         {0, 2},
                         {0, 3},
                         {1, 4},
                         {2, 4},
                         {3, 0},
                         {3, 1},
                         {3, 2},
                         {3, 3}}}}}},
    {'V',
     {.width = 3,
      .sections =
          {{.color = kWhite,
            .coords = {{0, 0}, {0, 1}, {0, 2}, {0, 3}, {1, 4}, {2, 0}, {2, 1}, {2, 2}, {2, 3}}}}}},
    {'W',
     {.width = 5,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 1},
                         {0, 2},
                         {0, 3},
                         {1, 4},
                         {2, 2},
                         {2, 3},
                         {3, 4},
                         {4, 0},
                         {4, 1},
                         {4, 2},
                         {4, 3}}}}}},
    {'X',
     {.width = 3,
      .sections =
          {{.color = kWhite,
            .coords = {{0, 0}, {0, 1}, {0, 3}, {0, 4}, {1, 2}, {2, 0}, {2, 1}, {2, 3}, {2, 4}}}}}},
    {'Y',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords = {{0, 0}, {0, 1}, {1, 2}, {1, 3}, {1, 4}, {2, 0}, {2, 1}}}}}},
    {'Z',
     {.width = 3,
      .sections =
          {{.color = kWhite,
            .coords = {{0, 0}, {0, 3}, {0, 4}, {1, 0}, {1, 2}, {1, 4}, {2, 0}, {2, 1}, {2, 4}}}}}},

    {'0',
     {.width = 4,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 1},
                         {0, 2},
                         {0, 3},
                         {1, 0},
                         {1, 2},
                         {1, 4},
                         {2, 0},
                         {2, 3},
                         {2, 4},
                         {3, 1},
                         {3, 2},
                         {3, 3}}}}}},
    {'1',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords = {{0, 1}, {0, 4}, {1, 0}, {1, 1}, {1, 2}, {1, 3}, {1, 4}, {2, 4}}}}}},
    {'2',
     {.width = 4,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 1},
                         {0, 4},
                         {1, 0},
                         {1, 3},
                         {1, 4},
                         {2, 0},
                         {2, 2},
                         {2, 4},
                         {3, 1},
                         {3, 4}}}}}},
    {'3',
     {.width = 4,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 0},
                         {0, 2},
                         {0, 4},
                         {1, 0},
                         {1, 2},
                         {1, 4},
                         {2, 0},
                         {2, 2},
                         {2, 4},
                         {3, 1},
                         {3, 3}}}}}},
    {'4',
     {.width = 4,
      .sections =
          {{.color = kWhite,
            .coords = {{0, 0}, {0, 1}, {1, 2}, {2, 2}, {3, 0}, {3, 1}, {3, 2}, {3, 3}, {3, 4}}}}}},
    {'5',
     {.width = 3,
      .sections =
          {{.color = kWhite,
            .coords = {{0, 0}, {0, 1}, {0, 2}, {0, 4}, {1, 0}, {1, 2}, {1, 4}, {2, 0}, {2, 3}}}}}},
    {'6',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords = {{0, 1}, {0, 2}, {0, 3}, {1, 0}, {1, 2}, {1, 4}, {2, 0}, {2, 3}}}}}},
    {'7',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords = {{0, 0}, {1, 0}, {1, 3}, {1, 4}, {2, 0}, {2, 1}, {2, 2}}}}}},
    {'8',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords = {{0, 1}, {0, 3}, {1, 0}, {1, 2}, {1, 4}, {2, 1}, {2, 3}}}}}},
    {'9',
     {.width = 3,
      .sections = {{.color = kWhite,
                    .coords = {{0, 1}, {1, 0}, {1, 2}, {2, 1}, {2, 2}, {2, 3}, {2, 4}}}}}},

    {'$',
     {.width = 4,
      .sections = {{.color = kWhite,
                    .coords =
                        {{0, 2},
                         {1, 1},
                         {1, 3},
                         {1, 5},
                         {2, 0},
                         {2, 1},
                         {2, 3},
                         {2, 5},
                         {2, 6},
                         {3, 4}}}}}},
    {'!',
     {.width = 1, .sections = {{.color = kWhite, .coords = {{0, 0}, {0, 1}, {0, 2}, {0, 4}}}}}},
    {'%',
     {.width = 5,
      .sections = {{.color = kWhite,
                    .coords = {{0, 1}, {0, 4}, {1, 3}, {2, 2}, {3, 1}, {4, 0}, {4, 3}}}}}},
};

struct TextPageImpl final : TextPage {
  const std::vector<SpritePlacement> &sprites() final { return _sprites; }

  void setText(const std::string &text) final {
    _sprites.clear();
    _sprites.reserve(text.size());

    for (auto x = 0, n = 0; n < text.size(); ++n) {
      if (text[n] == ' ' || text[n] == '+') {
        x += 3;
        continue;
      }
      auto it = kAlphaMap.find(text[n]);
      if (it == kAlphaMap.end()) {
        continue;
      }
      auto &glyph = it->second;
      _sprites.push_back({.pos = {x, 3}, .sprite = &glyph, .scale = {1, 2}});
      x += glyph.width + 1;
    }
  }

 private:
  std::vector<SpritePlacement> _sprites;
};

std::unique_ptr<TextPage> TextPage::create() { return std::make_unique<TextPageImpl>(); }

}  // namespace font
